name: Install VOICEVOX
on: push
env:
  VOICEVOX_VERSION: 0.11.4
jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
      - run: docker run --rm -it -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest
      - run: curl localhost:50021